# -*- coding: utf-8 -*-
"""Proyecto con 3 Agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfxpIm_L9iC3Lb3FEwW2dNMSqkOPmxNY

* ============================================
# BLOQUE 0: CONFIGURACIÓN INICIAL
* ============================================
* Este bloque solo se ejecuta una vez al inicio
* Instala librerías necesarias y monta Google Drive
"""

!pip install pandas numpy scikit-learn matplotlib seaborn wordcloud openpyxl

# Montar Google Drive para guardar los resultados
from google.colab import drive
drive.mount('/content/drive')

# Crear carpeta para el proyecto
!mkdir -p /content/drive/MyDrive/steam_agents_project

import pandas as pd
import numpy as np
import re
import json
from datetime import datetime

print("Entorno configurado correctamente")
print(f"Sesión iniciada: {datetime.now()}")

"""* ============================================
# BLOQUE 1: CARGA DEL DATASET
* ============================================

"""

# Opción 1: Subir desde tu computadora
from google.colab import files
print("Por favor, sube el archivo steam_games.csv")
# uploaded = files.upload()

# Opción 2: Cargar desde Google Drive (recomendado)
file_path = '/content/drive/MyDrive/steam_games.csv'
df_raw = pd.read_csv(file_path)

print(f"Dataset cargado correctamente")
print(f"Dimensiones: {df_raw.shape[0]} filas × {df_raw.shape[1]} columnas")
print(f"Columnas: {list(df_raw.columns)}")
print("\nPrimeras 5 filas:")
df_raw.head()

"""* ============================================
# BLOQUE 2: ANÁLISIS EXPLORATORIO INICIAL
* ============================================
"""

print("="*60)
print("DIAGNÓSTICO DEL DATASET")
print("="*60)

# 1. Tipos de datos
print("\nTIPOS DE DATOS:")
print(df_raw.dtypes.value_counts())

# 2. Valores nulos por columna
print("\nVALORES NULOS (top 10):")
nulls = df_raw.isnull().sum()
nulls_percent = (nulls / len(df_raw)) * 100
null_df = pd.DataFrame({'Nulos': nulls, 'Porcentaje': nulls_percent})
print(null_df[null_df['Nulos'] > 0].sort_values('Nulos', ascending=False).head(10))

# 3. Estadísticas básicas de columnas numéricas
print("\nESTADÍSTICAS COLUMNAS NUMÉRICAS:")
print(df_raw.describe())

# 4. Muestras de columnas problemáticas
print("\nMUESTRAS DE COLUMNAS PROBLEMÁTICAS:")
print("\n--- Precios (original_price) ---")
print(f"Valores únicos: {df_raw['original_price'].nunique()}")
print(f"Ejemplos: {df_raw['original_price'].dropna().head(10).tolist()}")

print("\n--- Reseñas (recent_reviews) ---")
print(f"Ejemplos:\n{df_raw['recent_reviews'].dropna().head(5)}")

print("\n--- Fechas (release_date) ---")
print(f"Ejemplos: {df_raw['release_date'].dropna().head(10).tolist()}")

print("\n--- Géneros (genre) ---")
print(f"Ejemplos: {df_raw['genre'].dropna().head(5)}")

