# -*- coding: utf-8 -*-
"""Proyecto con 3 Agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfxpIm_L9iC3Lb3FEwW2dNMSqkOPmxNY

* ============================================
# BLOQUE 0: CONFIGURACIÓN INICIAL
* ============================================
* Este bloque solo se ejecuta una vez al inicio
* Instala librerías necesarias y monta Google Drive
"""

!pip install pandas numpy scikit-learn matplotlib seaborn wordcloud openpyxl

# Montar Google Drive para guardar los resultados
from google.colab import drive
drive.mount('/content/drive')

# Crear carpeta para el proyecto
!mkdir -p /content/drive/MyDrive/steam_agents_project

import pandas as pd
import numpy as np
import re
import json
from datetime import datetime

print("Entorno configurado correctamente")
print(f"Sesión iniciada: {datetime.now()}")

"""* ============================================
# BLOQUE 1: CARGA DEL DATASET
* ============================================

"""

# Opción 1: Subir desde tu computadora
from google.colab import files
print("Por favor, sube el archivo steam_games.csv")
# uploaded = files.upload()

# Opción 2: Cargar desde Google Drive (recomendado)
file_path = '/content/drive/MyDrive/steam_games.csv'
df_raw = pd.read_csv(file_path)

print(f"Dataset cargado correctamente")
print(f"Dimensiones: {df_raw.shape[0]} filas × {df_raw.shape[1]} columnas")
print(f"Columnas: {list(df_raw.columns)}")
print("\nPrimeras 5 filas:")
df_raw.head()

"""* ============================================
# BLOQUE 2: ANÁLISIS EXPLORATORIO INICIAL
* ============================================
"""

print("="*60)
print("DIAGNÓSTICO DEL DATASET")
print("="*60)

# 1. Tipos de datos
print("\nTIPOS DE DATOS:")
print(df_raw.dtypes.value_counts())

# 2. Valores nulos por columna
print("\nVALORES NULOS (top 10):")
nulls = df_raw.isnull().sum()
nulls_percent = (nulls / len(df_raw)) * 100
null_df = pd.DataFrame({'Nulos': nulls, 'Porcentaje': nulls_percent})
print(null_df[null_df['Nulos'] > 0].sort_values('Nulos', ascending=False).head(10))

# 3. Estadísticas básicas de columnas numéricas
print("\nESTADÍSTICAS COLUMNAS NUMÉRICAS:")
print(df_raw.describe())

# 4. Muestras de columnas problemáticas
print("\nMUESTRAS DE COLUMNAS PROBLEMÁTICAS:")
print("\n--- Precios (original_price) ---")
print(f"Valores únicos: {df_raw['original_price'].nunique()}")
print(f"Ejemplos: {df_raw['original_price'].dropna().head(10).tolist()}")

print("\n--- Reseñas (recent_reviews) ---")
print(f"Ejemplos:\n{df_raw['recent_reviews'].dropna().head(5)}")

print("\n--- Fechas (release_date) ---")
print(f"Ejemplos: {df_raw['release_date'].dropna().head(10).tolist()}")

print("\n--- Géneros (genre) ---")
print(f"Ejemplos: {df_raw['genre'].dropna().head(5)}")

"""* ============================================
# BLOQUE 3: CLASE NORMALIZADOR - DEFINICIÓN
* ============================================
* Definimos la clase completa del Agente 1
"""

# -*- coding: utf-8 -*-
import re
import json
import numpy as np
import pandas as pd
import joblib
from sklearn.preprocessing import StandardScaler, LabelEncoder
from datetime import datetime

class SteamDataNormalizer:
    """
    AGENTE 1: Normalizador de datos de Steam
    Especializado en limpieza, imputación y transformación de datos de videojuegos
    """

    def __init__(self, df):
        self.original_df = df.copy()
        self.clean_df = df.copy()
        self.encoders = {}
        self.scalers = {}
        self.transformations_log = []

    def log_transform(self, message):
        timestamp = datetime.now().strftime("%H:%M:%S")
        log_entry = f"[{timestamp}] {message}"
        self.transformations_log.append(log_entry)
        print(f"{message}")

    def clean_prices(self):
        self.log_transform("Iniciando limpieza de precios")

        def extract_price(value):
            if pd.isna(value):
                return np.nan

            value_str = str(value).lower().strip()

            free_keywords = ['free', 'free to play', 'play for free', 'demo', 'free to use']
            if any(kw in value_str for kw in free_keywords):
                return 0.0

            price_match = re.search(r'(\d+[\.,]\d{2})|(\d+)', value_str)
            if price_match:
                price_str = price_match.group(0).replace(',', '.')
                try:
                    return float(price_str)
                except ValueError:
                    return np.nan

            return np.nan

        self.clean_df['price_clean'] = self.clean_df['original_price'].apply(extract_price)

        if 'discount_price' in self.clean_df.columns:
            self.clean_df['discount_clean'] = self.clean_df['discount_price'].apply(extract_price)
            self.clean_df['discount_clean'] = self.clean_df['discount_clean'].fillna(self.clean_df['price_clean'])

            mask = (self.clean_df['discount_clean'] < self.clean_df['price_clean']) & (self.clean_df['price_clean'] > 0)
            self.clean_df['discount_percent'] = np.where(
                mask,
                100 * (1 - self.clean_df['discount_clean'] / self.clean_df['price_clean']),
                0
            )

        self.log_transform("Precios limpiados exitosamente")
        return self

    def process_reviews(self):
        self.log_transform("Procesando reseñas")

        def parse_review(review_text):
            if pd.isna(review_text):
                return {'sentiment': 'No reviews', 'count': 0, 'percentage': 0}

            text = str(review_text)

            sentiment_match = re.match(r'^([^,\-]+)', text)
            sentiment = sentiment_match.group(1).strip() if sentiment_match else 'Unknown'

            count_match = re.search(r'\(([\d,]+)\)', text)
            count = int(count_match.group(1).replace(',', '')) if count_match else 0

            percent_match = re.search(r'(\d+)%', text)
            percentage = float(percent_match.group(1)) if percent_match else 0

            return {'sentiment': sentiment, 'count': count, 'percentage': percentage}

        for col in ['recent_reviews', 'all_reviews']:
            if col in self.clean_df.columns:
                parsed = self.clean_df[col].apply(parse_review)
                self.clean_df[f'{col}_sentiment'] = parsed.apply(lambda x: x['sentiment'])
                self.clean_df[f'{col}_count'] = parsed.apply(lambda x: x['count'])
                self.clean_df[f'{col}_percentage'] = parsed.apply(lambda x: x['percentage'])

        self.log_transform("Reseñas procesadas")
        return self

    def normalize_dates(self):
        self.log_transform("Normalizando fechas")

        self.clean_df['release_date_parsed'] = pd.to_datetime(
            self.clean_df['release_date'],
            errors='coerce'
        )

        self.clean_df['release_year'] = self.clean_df['release_date_parsed'].dt.year
        self.clean_df['release_month'] = self.clean_df['release_date_parsed'].dt.month
        self.clean_df['release_quarter'] = self.clean_df['release_date_parsed'].dt.quarter
        self.clean_df['release_dayofweek'] = self.clean_df['release_date_parsed'].dt.dayofweek

        self.clean_df['is_weekend_release'] = (self.clean_df['release_dayofweek'] >= 5).astype(float)
        self.clean_df['is_old_game'] = (self.clean_df['release_year'] < 2010).astype(float)

        self.log_transform("Fechas normalizadas")
        return self

    def parse_list_column(self, column_name):
        self.log_transform(f"Procesando columna lista: {column_name}")

        def safe_parse(value):
            if pd.isna(value):
                return []
            val_str = str(value).strip()
            if val_str.startswith('[') and val_str.endswith(']'):
                try:
                    val_clean = val_str.replace("'", '"')
                    return json.loads(val_clean)
                except:
                    return [x.strip().replace("'", "").replace('"', '') for x in val_str[1:-1].split(',')]
            else:
                return [x.strip() for x in val_str.split(',') if x.strip()]

        self.clean_df[f'{column_name}_list'] = self.clean_df[column_name].apply(safe_parse)
        self.clean_df[f'{column_name}_count'] = self.clean_df[f'{column_name}_list'].apply(len)

        self.log_transform(f"Columna {column_name} procesada")
        return self

    def impute_missing_values(self):
        self.log_transform("Imputando valores faltantes")

        text_cols = ['developer', 'publisher', 'recent_reviews_sentiment', 'all_reviews_sentiment']
        for col in text_cols:
            if col in self.clean_df.columns:
                self.clean_df[col] = self.clean_df[col].fillna('Unknown')

        desc_cols = ['desc_snippet', 'about_the_game']
        for col in desc_cols:
            if col in self.clean_df.columns:
                self.clean_df[col] = self.clean_df[col].fillna('')

        numeric_cols = self.clean_df.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            if self.clean_df[col].isnull().any():
                median_val = self.clean_df[col].median()
                self.clean_df[col] = self.clean_df[col].fillna(median_val if not pd.isna(median_val) else 0)

        self.log_transform("Valores faltantes imputados")
        return self

    def encode_categorical(self, columns_to_encode):
        self.log_transform(f"Codificando variables categóricas: {columns_to_encode}")
        for col in columns_to_encode:
            if col in self.clean_df.columns:
                encoder = LabelEncoder()
                self.clean_df[col] = self.clean_df[col].fillna('Unknown').astype(str)
                self.clean_df[f'{col}_encoded'] = encoder.fit_transform(self.clean_df[col])
                self.encoders[col] = encoder
        self.log_transform("Variables categóricas codificadas")
        return self

    def scale_numeric(self, columns_to_scale):
        self.log_transform(f"Escalando variables numéricas: {columns_to_scale}")
        for col in columns_to_scale:
            if col in self.clean_df.columns:
                scaler = StandardScaler()
                self.clean_df[col] = self.clean_df[col].fillna(0)
                values = self.clean_df[col].values.reshape(-1, 1)
                self.clean_df[f'{col}_scaled'] = scaler.fit_transform(values)
                self.scalers[col] = scaler
        self.log_transform("Variables numéricas escaladas")
        return self

    def create_target_variable(self):
        self.log_transform("Creando variable objetivo")
        if 'all_reviews_percentage' in self.clean_df.columns and 'all_reviews_count' in self.clean_df.columns:
            pct = self.clean_df['all_reviews_percentage'].fillna(0)
            cnt = self.clean_df['all_reviews_count'].fillna(0)

            self.clean_df['game_score'] = pct * np.log1p(cnt)
            max_score = self.clean_df['game_score'].max()
            if max_score > 0:
                self.clean_df['game_score_normalized'] = 100 * self.clean_df['game_score'] / max_score
            else:
                self.clean_df['game_score_normalized'] = 0
        self.log_transform("Variable objetivo creada")
        return self

    def get_clean_data(self):
        return self.clean_df, self.transformations_log

    def save_clean_data(self, path):
        df_to_save = self.clean_df.copy()
        for col in df_to_save.columns:
            if col.endswith('_list'):
                df_to_save[col] = df_to_save[col].apply(json.dumps)

        df_to_save.to_parquet(path, index=False)
        self.log_transform(f"Dataset guardado en {path}")

        log_path = path.replace('.parquet', '_transformations.json')
        with open(log_path, 'w') as f:
            json.dump(self.transformations_log, f, indent=2)
        return self


# ============================================================================
# SUB-CLASE OPTIMIZADA: PERSISTENCIA, CALIDAD Y DESCARTE DE RAM PROTEGIDO
# ============================================================================

class SteamDataNormalizerOptimized(SteamDataNormalizer):
    """
    Versión profesional del Agente 1 que añade capacidades de persistencia
    para el Agente 2 y validación estructurada para el Agente 3.
    """

    def __init__(self, df):
        super().__init__(df)
        self.quality_metrics = {}
        self.param_path = None

    def save_parameters(self, path):
        """Guarda los transformadores entrenados para que los use el Agente 2"""
        params = {
            'scalers': self.scalers,
            'encoders': self.encoders,
            'transformations_log': self.transformations_log,
            'final_columns': list(self.clean_df.columns),
            'quality_metrics': self.quality_metrics
        }
        joblib.dump(params, path)
        self.param_path = path
        self.log_transform(f"Parámetros e inspectores guardados con éxito en: {path}")
        return self

    def validate_quality(self):
        """Construye un diagnóstico de calidad para el reporte del Agente 3 sin romper con columnas de tipo lista"""
        self.log_transform("Ejecutando auditoría de calidad sobre datos limpios")

        # FIX: Filtrar variables tipo lista para calcular duplicados de forma segura
        cols_para_duplicados = [c for c in self.clean_df.columns if not c.endswith('_list')]

        metrics = {
            'total_registros': len(self.clean_df),
            'total_columnas': len(self.clean_df.columns),
            'nulos_totales': int(self.clean_df.isnull().sum().sum()),
            'duplicados_totales': int(self.clean_df.duplicated(subset=cols_para_duplicados).sum()),
            'uso_memoria_mb': self.clean_df.memory_usage(deep=True).sum() / 1024**2
        }

        if 'game_score_normalized' in self.clean_df.columns:
            metrics['rango_score_target'] = [
                float(self.clean_df['game_score_normalized'].min()),
                float(self.clean_df['game_score_normalized'].max())
            ]
        if 'price_clean' in self.clean_df.columns:
            metrics['precios_negativos'] = int((self.clean_df['price_clean'] < 0).sum())

        self.quality_metrics = metrics
        self.log_transform(f"Auditoría terminada. Nulos huérfanos: {metrics['nulos_totales']}")
        return metrics

    def remove_intermediate_columns(self, keep_cols=None):
        """Elimina las columnas intermedias temporales para optimizar consumo en memoria"""
        if keep_cols is None:
            keep_cols = [
                'price_clean', 'discount_percent', 'release_year', 'release_month',
                'is_weekend_release', 'is_old_game', 'genre_count', 'popular_tags_count',
                'all_reviews_count', 'recent_reviews_count', 'all_reviews_percentage',
                'game_score_normalized', 'type_encoded', 'developer_encoded', 'publisher_encoded',
                'price_clean_scaled', 'all_reviews_count_scaled', 'recent_reviews_count_scaled'
            ]

        id_cols = ['name', 'app_name', 'url']
        for col in id_cols:
            if col in self.clean_df.columns:
                keep_cols.append(col)

        list_cols = [c for c in self.clean_df.columns if c.endswith('_list')]
        keep_cols.extend(list_cols)

        existentes = [c for c in keep_cols if c in self.clean_df.columns]
        self.clean_df = self.clean_df[existentes]

        self.log_transform(f"Limpieza de RAM: Columnas reducidas a {len(existentes)} variables esenciales.")
        return self

"""* ============================================
# BLOQUE 4: EJECUCIÓN DEL AGENTE 1
* ============================================
"""

# Crear instancia del normalizador optimizado con el dataset original
normalizer = SteamDataNormalizerOptimized(df_raw)

print("="*60)
print("AGENTE 1 OPTIMIZADO: INICIANDO PIPELINE DE PRODUCCIÓN")
print("="*60)

# --- FASE 1: EXTRACCIÓN Y LIMPIEZA INICIAL ---
# 1. Limpiar precios (maneja texto, gratuidad y convierte a float)
normalizer.clean_prices()

# 2. Procesar reseñas (extrae sentimiento, conteo y porcentaje por separado)
normalizer.process_reviews()

# 3. Normalizar fechas (convierte a datetime y extrae características temporales)
normalizer.normalize_dates()

# 4. Procesar columnas de texto estructurado en listas (géneros, tags, idiomas)
for col in ['genre', 'popular_tags', 'languages']:
    if col in normalizer.clean_df.columns:
        normalizer.parse_list_column(col)


# --- FASE 2: TRATAMIENTO DE VALORES FALTANTES ---
# 5. Imputar valores faltantes de forma inteligente
normalizer.impute_missing_values()


# --- FASE 3: PREPARACIÓN PARA MACHINE LEARNING ---
# 6. Codificar variables categóricas clave (LabelEncoder seguro sin nulos)
categorical_cols = ['type', 'developer', 'publisher']
normalizer.encode_categorical(categorical_cols)

# 7. Escalar variables numéricas importantes (StandardScaler)
numeric_cols = ['price_clean', 'all_reviews_count', 'recent_reviews_count']
normalizer.scale_numeric([c for c in numeric_cols if c in normalizer.clean_df.columns])


# --- FASE 4: INGENIERÍA DE CARACTERÍSTICAS (TARGET) ---
# 8. Crear variable objetivo basada en popularidad y aceptación
normalizer.create_target_variable()


# ============================================================
# 🔥 NUEVA FASE: OPTIMIZACIÓN, AUDITORÍA Y PERSISTENCIA
# ============================================================

# 9. Eliminar columnas intermedias para liberar espacio en RAM
normalizer.remove_intermediate_columns()

# 10. Ejecutar auditoría de calidad de datos
metrics = normalizer.validate_quality()

# 11. Guardar parámetros (scalers/encoders) para uso del Agente 2
normalizer.save_parameters('/content/drive/MyDrive/steam_agents_project/agent1_params.joblib')


# ============================================================
# OUTPUT Y REPORTES FINALES
# ============================================================
print("\n" + "="*60)
print("AGENTE 1: PIPELINE DE PRODUCCIÓN COMPLETADO")
print("="*60)

# Obtener dataframe limpio y optimizado junto a la bitácora
df_clean, transformations = normalizer.get_clean_data()

# Reporte de métricas de rendimiento y calidad del agente
print(f"\nDataset limpio dimensiones: {df_clean.shape}")
print(f"Nuevas columnas finales: {len(df_clean.columns) - len(df_raw.columns)} respecto al original")
print(f"Transformaciones registradas en el log: {len(transformations)}")

print("\nResumen de Auditoría de Calidad:")
print(f"   → Valores nulos remanentes en el dataset: {metrics['nulos_totales']}")
print(f"   → Filas duplicadas detectadas: {metrics['duplicados_totales']}")
print(f"   → Consumo de RAM estimado del DataFrame: {metrics['uso_memoria_mb']:.2f} MB")

# Ver muestra del dataset procesado
print("\nMuestra del dataset limpio final:")
df_clean.head()

"""* ============================================
# BLOQUE 5: GUARDAR DATASET LIMPIO
* ============================================
* Guardamos el resultado del Agente 1 para el Agente 2
"""

# Guardar en Google Drive
save_path = '/content/drive/MyDrive/steam_agents_project/steam_games_clean.parquet'
normalizer.save_clean_data(save_path)

# También guardar una versión CSV para inspección manual
csv_path = '/content/drive/MyDrive/steam_agents_project/steam_games_clean.csv'
df_clean.to_csv(csv_path, index=False)

print("="*60)
print("DATASET LIMPIO GUARDADO")
print("="*60)
print(f"Ubicación: {save_path}")
print(f"CSV: {csv_path}")

# Estadísticas finales
print("\nESTADÍSTICAS FINALES:")
print(f"   - Filas: {len(df_clean):,}")
print(f"   - Columnas: {len(df_clean.columns)}")
print(f"   - Valores nulos restantes: {df_clean.isnull().sum().sum():,}")
print(f"   - Memoria utilizada: {df_clean.memory_usage(deep=True).sum() / 1024**2:.2f} MB")

"""* ============================================
# BLOQUE 6: VISUALIZACIÓN DE RESULTADOS
* ============================================
* Verificamos visualmente las transformaciones
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('seaborn-v0_8-darkgrid')
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# 1. Distribución de precios
ax1 = axes[0, 0]
price_data = df_clean[df_clean['price_clean'] < 100]['price_clean']
ax1.hist(price_data, bins=50, edgecolor='black', alpha=0.7)
ax1.set_title('Distribución de Precios (juegos < $100)', fontsize=12)
ax1.set_xlabel('Precio ($)')
ax1.set_ylabel('Frecuencia')

# 2. Score de juegos
ax2 = axes[0, 1]
if 'game_score_normalized' in df_clean.columns:
    ax2.hist(df_clean['game_score_normalized'].dropna(), bins=30, edgecolor='black', alpha=0.7, color='green')
    ax2.set_title('Distribución del Score de Juegos', fontsize=12)
    ax2.set_xlabel('Score Normalizado (0-100)')
    ax2.set_ylabel('Frecuencia')

# 3. Lanzamientos por año
ax3 = axes[1, 0]
year_counts = df_clean['release_year'].value_counts().sort_index()
year_counts = year_counts[year_counts.index >= 1990]  # Filtrar años recientes
ax3.bar(year_counts.index, year_counts.values, alpha=0.7, color='orange')
ax3.set_title('Lanzamientos por Año', fontsize=12)
ax3.set_xlabel('Año')
ax3.set_ylabel('Cantidad de Juegos')

# 4. Top géneros
ax4 = axes[1, 1]
if 'genre_count' in df_clean.columns:
    # Explotar la lista de géneros para contar
    all_genres = []
    for genres in df_clean['genre_list'].dropna():
        all_genres.extend(genres)

    from collections import Counter
    genre_counts = Counter(all_genres)
    top_genres = dict(sorted(genre_counts.items(), key=lambda x: x[1], reverse=True)[:10])

    ax4.barh(list(top_genres.keys()), list(top_genres.values()), alpha=0.7, color='purple')
    ax4.set_title('Top 10 Géneros más Comunes', fontsize=12)
    ax4.set_xlabel('Cantidad de Juegos')

plt.tight_layout()
plt.savefig('/content/drive/MyDrive/steam_agents_project/visualizations.png', dpi=150, bbox_inches='tight')
plt.show()

print("Visualizaciones guardadas")


"""============================================
# BLOQUE 7: AGENTE 2 - ENTRENADOR DE MODELOS
============================================
* Responsabilidad: Validación, entrenamiento y selección del mejor modelo
"""

import joblib
import pandas as pd
import numpy as np
import json
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import warnings
warnings.filterwarnings('ignore')

class AgenteEntrenador:
    """
    AGENTE 2: Entrenador de modelos de Machine Learning
    Especializado en validación, entrenamiento y selección de modelos
    """

    def __init__(self, clean_data_path, params_path):
        """
        Inicializa el agente cargando el dataset limpio y los parámetros del Agente 1
        """
        print("="*60)
        print("AGENTE 2: INICIANDO ENTRENADOR")
        print("="*60)

        # Cargar dataset limpio
        self.df = pd.read_parquet(clean_data_path)
        print(f"Dataset cargado: {self.df.shape[0]} filas × {self.df.shape[1]} columnas")

        # Cargar parámetros del Agente 1 (Scalers, Encoders, Logs)
        self.params = joblib.load(params_path)
        print(f"Parámetros del Agente 1 cargados con éxito")

        # Inicializar atributos
        self.X_train = None
        self.X_test = None
        self.y_train = None
        self.y_test = None
        self.models = {}
        self.results = {}
        self.best_model = None
        self.best_model_name = None
        self.best_metrics = {}

    def prepare_features(self, target_col='game_score_normalized', test_size=0.2, random_state=42):
        """
        Prepara las características (X) y el target (y) evitando colinealidad y fugas de datos
        """
        print("\n" + "-"*40)
        print("PREPARANDO CARACTERÍSTICAS PARA ENTRAR A LOS MODELOS")
        print("-"*40)

        if target_col not in self.df.columns:
            raise ValueError(f"Columna objetivo '{target_col}' no encontrada en el dataset")

        # 1. EXCLUSIÓN ESTRICTA: Evitamos meter la variable original si ya usamos la versión escalada (_scaled)
        # También dejamos fuera identificadores, textos descriptivos y estructuras de listas.
        exclude_cols = [
            target_col, 'game_score', 'name', 'app_name', 'url', 'desc_snippet', 'about_the_game',
            'developer', 'publisher', 'type', 'all_reviews', 'recent_reviews',
            # Dejar fuera las originales si existen sus versiones escaladas en el dataset
            'price_clean', 'all_reviews_count', 'recent_reviews_count'
        ]

        # Filtrar nombres de columnas que no estén en la lista de exclusión y que no sean listas descriptivas
        feature_cols = [col for col in self.df.columns if col not in exclude_cols and not col.endswith('_list')]

        # Filtrar estrictamente solo columnas numéricas remanentes
        X = self.df[feature_cols].select_dtypes(include=[np.number])
        y = self.df[target_col]

        # Eliminar filas donde el target sea nulo de manera huérfana
        mask = ~y.isnull()
        X = X[mask]
        y = y[mask]

        # Dividir conjuntos de datos
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(
            X, y, test_size=test_size, random_state=random_state
        )

        print(f"Matriz de características X: {X.shape[1]} columnas seleccionadas.")
        print(f"   → Variables predictoras finales: {list(X.columns)}")
        print(f"División completada: Train = {len(self.X_train)} | Test = {len(self.X_test)}")

        return self

    def train_models(self):
        """
        Entrenamientos en paralelo de los modelos candidatos y validación cruzada robusta
        """
        print("\n" + "-"*40)
        print("EVALUANDO CANDIDATOS EN ARENA DE ENTRENAMIENTO")
        print("-"*40)

        models_to_train = {
            'Random Forest': RandomForestRegressor(n_estimators=100, max_depth=15, random_state=42, n_jobs=-1),
            'Gradient Boosting': GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42),
            'Ridge Regression': Ridge(alpha=1.0),
            'Lasso Regression': Lasso(alpha=0.01)
        }

        cv = KFold(n_splits=5, shuffle=True, random_state=42)

        for name, model in models_to_train.items():
            print(f"Procesando {name}...")

            # Ajustar modelo
            model.fit(self.X_train, self.y_train)

            y_pred_train = model.predict(self.X_train)
            y_pred_test = model.predict(self.X_test)

            # Extracción de métricas estándar de regresión
            metrics = {
                'train_r2': float(r2_score(self.y_train, y_pred_train)),
                'test_r2': float(r2_score(self.y_test, y_pred_test)),
                'train_rmse': float(np.sqrt(mean_squared_error(self.y_train, y_pred_train))),
                'test_rmse': float(np.sqrt(mean_squared_error(self.y_test, y_pred_test))),
                'train_mae': float(mean_absolute_error(self.y_train, y_pred_train)),
                'test_mae': float(mean_absolute_error(self.y_test, y_pred_test))
            }

            # Validación Cruzada
            try:
                cv_scores = cross_val_score(model, self.X_train, self.y_train, cv=cv, scoring='r2', n_jobs=-1)
                metrics['cv_r2_mean'] = float(cv_scores.mean())
                metrics['cv_r2_std'] = float(cv_scores.std())
            except Exception as e:
                metrics['cv_r2_mean'] = 0.0
                metrics['cv_r2_std'] = 0.0

            self.models[name] = model
            self.results[name] = metrics

            print(f"   → R² Test: {metrics['test_r2']:.4f} | CV R² Mean: {metrics['cv_r2_mean']:.4f} | RMSE: {metrics['test_rmse']:.4f}")

        return self

    def select_best_model(self, metric='test_r2'):
        """
        Selecciona el algoritmo ganador basándose en la métrica competitiva elegida
        """
        print("\n" + "-"*40)
        print("SELECCIONANDO EL MODELO GANADOR")
        print("-"*40)

        higher_is_better = metric in ['test_r2', 'cv_r2_mean', 'train_r2']
        best_score = -np.inf if higher_is_better else np.inf
        best_name = None

        for name, metrics in self.results.items():
            score = metrics.get(metric, -np.inf if higher_is_better else np.inf)
            if higher_is_better and score > best_score:
                best_score = score
                best_name = name
            elif not higher_is_better and score < best_score:
                best_score = score
                best_name = name

        self.best_model_name = best_name
        self.best_model = self.models[best_name]
        self.best_metrics = self.results[best_name]

        print(f"¡Modelo Ganador seleccionado!: {best_name}")
        print(f"Desempeño bajo métrica '{metric}': {best_score:.4f}")
        return self

    def hyperparameter_tuning(self):
        """
        Ajuste fino opcional por Grid Search para exprimir el rendimiento del ganador
        """
        print("\n" + "-"*40)
        print(f"OPTIMIZANDO HIPERPARÁMETROS: {self.best_model_name}")
        print("-"*40)

        if self.best_model_name == 'Random Forest':
            param_grid = {
                'n_estimators': [100, 150],
                'max_depth': [12, 15, None],
                'min_samples_split': [2, 5]
            }
            base_model = RandomForestRegressor(random_state=42, n_jobs=-1)
        elif self.best_model_name == 'Gradient Boosting':
            param_grid = {
                'n_estimators': [100, 150],
                'learning_rate': [0.05, 0.1],
                'max_depth': [4, 5]
            }
            base_model = GradientBoostingRegressor(random_state=42)
        else:
            print(f"El tuning no es crítico o no está configurado para {self.best_model_name}.")
            return self

        grid = GridSearchCV(base_model, param_grid, cv=3, scoring='r2', n_jobs=-1)
        grid.fit(self.X_train, self.y_train)

        print(f"   → Mejores parámetros: {grid.best_params_}")
        print(f"   → R² optimizado en CV: {grid.best_score_:.4f}")

        self.best_model = grid.best_estimator_
        self.best_metrics['cv_r2_mean'] = float(grid.best_score_)
        return self

    def save_model(self, path):
        """
        Empaqueta el modelo entrenado y exporta un JSON limpio de métricas para el Agente 3
        """
        model_package = {
            'model': self.best_model,
            'model_name': self.best_model_name,
            'metrics': self.best_metrics,
            'features': list(self.X_train.columns),
            'train_size': len(self.X_train),
            'test_size': len(self.X_test),
            'results_summary': self.results
        }

        # Guardar binario del modelo
        joblib.dump(model_package, path)
        print(f"\nBinario del modelo guardado en: {path}")

        # Guardar JSON de métricas para el Agente Supervisor (Agente 3)
        metrics_path = path.replace('.joblib', '_metrics.json')
        with open(metrics_path, 'w') as f:
            json.dump(self.best_metrics, f, indent=2)

        print(f"Reporte JSON de métricas exportado en: {metrics_path}")
        return self

"""============================================
# BLOQUE 8: EJECUCIÓN CONTINUA DEL PIPELINE DEL AGENTE 2
============================================
"""

# 1. Instanciar el Agente Entrenador cargando las salidas previas
entrenador = AgenteEntrenador(
    clean_data_path='/content/drive/MyDrive/steam_agents_project/steam_games_clean.parquet',
    params_path='/content/drive/MyDrive/steam_agents_project/agent1_params.joblib'
)

# 2. Segmentar variables predictoras evitando redundancia numérica
entrenador.prepare_features(target_col='game_score_normalized', test_size=0.2, random_state=42)

# 3. Lanzar entrenamiento simultáneo de modelos competidores
entrenador.train_models()

# 4. Seleccionar el algoritmo con mejor coeficiente de determinación R²
entrenador.select_best_model(metric='test_r2')

# 5. Opcional: Descomentar la siguiente línea para activar optimización por grilla
# entrenador.hyperparameter_tuning()

# 6. Serializar artefactos finales para el Agente Comunicador
entrenador.save_model('/content/drive/MyDrive/steam_agents_project/best_model.joblib')

# 7. Desplegar Feature Importance si el modelo ganador lo soporta (Modelos basados en Árboles)
if hasattr(entrenador.best_model, 'feature_importances_'):
    print("\nTOP 10 VARIABLES CON MAYOR PESO PREDICTOR (FEATURE IMPORTANCE):")
    importances = entrenador.best_model.feature_importances_
    features = entrenador.X_train.columns
    fi_df = pd.DataFrame({'feature': features, 'importance': importances}).sort_values('importance', ascending=False).head(10)

    for idx, row in fi_df.iterrows():
        print(f"   → Variable: {row['feature']:<30} | Impacto: {row['importance']:.4f}")

print("\n" + "="*60)
print("PIPELINE DEL AGENTE 2 CONCLUIDO CON ÉXITO")
print("="*60)