# -*- coding: utf-8 -*-
"""Proyecto con 3 Agentes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NfxpIm_L9iC3Lb3FEwW2dNMSqkOPmxNY

* ============================================
# BLOQUE 0: CONFIGURACIÓN INICIAL
* ============================================
* Este bloque solo se ejecuta una vez al inicio
* Instala librerías necesarias y monta Google Drive
"""

!pip install pandas numpy scikit-learn matplotlib seaborn wordcloud openpyxl

# Montar Google Drive para guardar los resultados
from google.colab import drive
drive.mount('/content/drive')

# Crear carpeta para el proyecto
!mkdir -p /content/drive/MyDrive/steam_agents_project

import pandas as pd
import numpy as np
import re
import json
from datetime import datetime

print("Entorno configurado correctamente")
print(f"Sesión iniciada: {datetime.now()}")

"""* ============================================
# BLOQUE 1: CARGA DEL DATASET
* ============================================

"""

# Opción 1: Subir desde tu computadora
from google.colab import files
print("Por favor, sube el archivo steam_games.csv")
# uploaded = files.upload()

# Opción 2: Cargar desde Google Drive (recomendado)
file_path = '/content/drive/MyDrive/steam_games.csv'
df_raw = pd.read_csv(file_path)

print(f"Dataset cargado correctamente")
print(f"Dimensiones: {df_raw.shape[0]} filas × {df_raw.shape[1]} columnas")
print(f"Columnas: {list(df_raw.columns)}")
print("\nPrimeras 5 filas:")
df_raw.head()

"""* ============================================
# BLOQUE 2: ANÁLISIS EXPLORATORIO INICIAL
* ============================================
"""

print("="*60)
print("DIAGNÓSTICO DEL DATASET")
print("="*60)

# 1. Tipos de datos
print("\nTIPOS DE DATOS:")
print(df_raw.dtypes.value_counts())

# 2. Valores nulos por columna
print("\nVALORES NULOS (top 10):")
nulls = df_raw.isnull().sum()
nulls_percent = (nulls / len(df_raw)) * 100
null_df = pd.DataFrame({'Nulos': nulls, 'Porcentaje': nulls_percent})
print(null_df[null_df['Nulos'] > 0].sort_values('Nulos', ascending=False).head(10))

# 3. Estadísticas básicas de columnas numéricas
print("\nESTADÍSTICAS COLUMNAS NUMÉRICAS:")
print(df_raw.describe())

# 4. Muestras de columnas problemáticas
print("\nMUESTRAS DE COLUMNAS PROBLEMÁTICAS:")
print("\n--- Precios (original_price) ---")
print(f"Valores únicos: {df_raw['original_price'].nunique()}")
print(f"Ejemplos: {df_raw['original_price'].dropna().head(10).tolist()}")

print("\n--- Reseñas (recent_reviews) ---")
print(f"Ejemplos:\n{df_raw['recent_reviews'].dropna().head(5)}")

print("\n--- Fechas (release_date) ---")
print(f"Ejemplos: {df_raw['release_date'].dropna().head(10).tolist()}")

print("\n--- Géneros (genre) ---")
print(f"Ejemplos: {df_raw['genre'].dropna().head(5)}")

"""* ============================================
# BLOQUE 3: CLASE NORMALIZADOR - DEFINICIÓN
* ============================================
* Definimos la clase completa del Agente 1
"""

import re
import json
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from datetime import datetime

class SteamDataNormalizer:
    """
    AGENTE 1: Normalizador de datos de Steam
    Especializado en limpieza, imputación y transformación de datos de videojuegos
    """

    def __init__(self, df):
        self.original_df = df.copy()
        self.clean_df = df.copy()
        self.encoders = {}
        self.scalers = {}
        self.transformations_log = []

    def log_transform(self, message):
        timestamp = datetime.now().strftime("%H:%M:%S")
        log_entry = f"[{timestamp}] {message}"
        self.transformations_log.append(log_entry)
        print(f"{message}")

    def clean_prices(self):
        self.log_transform("Iniciando limpieza de precios")

        def extract_price(value):
            if pd.isna(value):
                return np.nan

            value_str = str(value).lower().strip()

            # Palabras clave de gratuidad comunes en el dataset
            free_keywords = ['free', 'free to play', 'play for free', 'demo', 'free to use']
            if any(kw in value_str for kw in free_keywords):
                return 0.0

            # Regex mejorada: busca cualquier número decimal o entero
            price_match = re.search(r'(\d+[\.,]\d{2})|(\d+)', value_str)
            if price_match:
                # Reemplazar comas por puntos por si viene en formato europeo (ej: 9,99)
                price_str = price_match.group(0).replace(',', '.')
                try:
                    return float(price_str)
                except ValueError:
                    return np.nan

            return np.nan

        self.clean_df['price_clean'] = self.clean_df['original_price'].apply(extract_price)

        if 'discount_price' in self.clean_df.columns:
            self.clean_df['discount_clean'] = self.clean_df['discount_price'].apply(extract_price)
            # Si no hay precio de descuento, el precio base es el precio de "descuento"
            self.clean_df['discount_clean'] = self.clean_df['discount_clean'].fillna(self.clean_df['price_clean'])

            # Calcular porcentaje de descuento real
            mask = (self.clean_df['discount_clean'] < self.clean_df['price_clean']) & (self.clean_df['price_clean'] > 0)
            self.clean_df['discount_percent'] = np.where(
                mask,
                100 * (1 - self.clean_df['discount_clean'] / self.clean_df['price_clean']),
                0
            )

        self.log_transform("Precios limpiados exitosamente")
        return self

    def process_reviews(self):
        self.log_transform("Procesando reseñas")

        def parse_review(review_text):
            if pd.isna(review_text):
                return {'sentiment': 'No reviews', 'count': 0, 'percentage': 0}

            text = str(review_text)

            # En el dataset de Kaggle el formato suele ser: "Very Positive,(1,234) - 85% of the 1,234 user reviews..."
            sentiment_match = re.match(r'^([^,\-]+)', text)
            sentiment = sentiment_match.group(1).strip() if sentiment_match else 'Unknown'

            count_match = re.search(r'\(([\d,]+)\)', text)
            count = int(count_match.group(1).replace(',', '')) if count_match else 0

            percent_match = re.search(r'(\d+)%', text)
            percentage = float(percent_match.group(1)) if percent_match else 0

            return {'sentiment': sentiment, 'count': count, 'percentage': percentage}

        for col in ['recent_reviews', 'all_reviews']:
            if col in self.clean_df.columns:
                parsed = self.clean_df[col].apply(parse_review)
                self.clean_df[f'{col}_sentiment'] = parsed.apply(lambda x: x['sentiment'])
                self.clean_df[f'{col}_count'] = parsed.apply(lambda x: x['count'])
                self.clean_df[f'{col}_percentage'] = parsed.apply(lambda x: x['percentage'])

        self.log_transform("Reseñas procesadas")
        return self

    def normalize_dates(self):
        self.log_transform("Normalizando fechas")

        #errors='coerce' transformará lo que no entienda (ej: "Coming soon") en NaT
        self.clean_df['release_date_parsed'] = pd.to_datetime(
            self.clean_df['release_date'],
            errors='coerce'
        )

        self.clean_df['release_year'] = self.clean_df['release_date_parsed'].dt.year
        self.clean_df['release_month'] = self.clean_df['release_date_parsed'].dt.month
        self.clean_df['release_quarter'] = self.clean_df['release_date_parsed'].dt.quarter
        self.clean_df['release_dayofweek'] = self.clean_df['release_date_parsed'].dt.dayofweek

        self.clean_df['is_weekend_release'] = (self.clean_df['release_dayofweek'] >= 5).astype(float) # float por si quedan NaNs
        self.clean_df['is_old_game'] = (self.clean_df['release_year'] < 2010).astype(float)

        self.log_transform("Fechas normalizadas")
        return self

    def parse_list_column(self, column_name):
        self.log_transform(f"Procesando columna lista: {column_name}")

        def safe_parse(value):
            if pd.isna(value):
                return []
            # El dataset guarda las listas como strings "Action, Adventure, Casual"
            # O a veces emulando listas ['Action', 'Adventure']
            val_str = str(value).strip()
            if val_str.startswith('[') and val_str.endswith(']'):
                try:
                    val_clean = val_str.replace("'", '"')
                    return json.loads(val_clean)
                except:
                    return [x.strip().replace("'", "").replace('"', '') for x in val_str[1:-1].split(',')]
            else:
                return [x.strip() for x in val_str.split(',') if x.strip()]

        self.clean_df[f'{column_name}_list'] = self.clean_df[column_name].apply(safe_parse)
        self.clean_df[f'{column_name}_count'] = self.clean_df[f'{column_name}_list'].apply(len)

        self.log_transform(f"Columna {column_name} procesada")
        return self

    def impute_missing_values(self):
        self.log_transform("Imputando valores faltantes")

        text_cols = ['developer', 'publisher', 'recent_reviews_sentiment', 'all_reviews_sentiment']
        for col in text_cols:
            if col in self.clean_df.columns:
                self.clean_df[col] = self.clean_df[col].fillna('Unknown')

        desc_cols = ['desc_snippet', 'about_the_game']
        for col in desc_cols:
            if col in self.clean_df.columns:
                self.clean_df[col] = self.clean_df[col].fillna('')

        # Imputar numéricos con mediana de manera segura
        numeric_cols = self.clean_df.select_dtypes(include=[np.number]).columns
        for col in numeric_cols:
            if self.clean_df[col].isnull().any():
                median_val = self.clean_df[col].median()
                # Si toda la columna es NaN, la mediana es NaN, rellenamos con 0
                self.clean_df[col] = self.clean_df[col].fillna(median_val if not pd.isna(median_val) else 0)

        self.log_transform("Valores faltantes imputados")
        return self

    def encode_categorical(self, columns_to_encode):
        self.log_transform(f"Codificando variables categóricas: {columns_to_encode}")
        for col in columns_to_encode:
            if col in self.clean_df.columns:
                encoder = LabelEncoder()
                self.clean_df[col] = self.clean_df[col].fillna('Unknown').astype(str)
                self.clean_df[f'{col}_encoded'] = encoder.fit_transform(self.clean_df[col])
                self.encoders[col] = encoder
        self.log_transform("Variables categóricas codificadas")
        return self

    def scale_numeric(self, columns_to_scale):
        self.log_transform(f"Escalando variables numéricas: {columns_to_scale}")
        for col in columns_to_scale:
            if col in self.clean_df.columns:
                scaler = StandardScaler()
                # Asegurar que no vayan nulos al scaler
                self.clean_df[col] = self.clean_df[col].fillna(0)
                values = self.clean_df[col].values.reshape(-1, 1)
                self.clean_df[f'{col}_scaled'] = scaler.fit_transform(values)
                self.scalers[col] = scaler
        self.log_transform("Variables numéricas escaladas")
        return self

    def create_target_variable(self):
        self.log_transform("Creando variable objetivo")
        if 'all_reviews_percentage' in self.clean_df.columns and 'all_reviews_count' in self.clean_df.columns:
            # Asegurar nulos a 0 para operaciones aritméticas
            pct = self.clean_df['all_reviews_percentage'].fillna(0)
            cnt = self.clean_df['all_reviews_count'].fillna(0)

            self.clean_df['game_score'] = pct * np.log1p(cnt)
            max_score = self.clean_df['game_score'].max()
            if max_score > 0:
                self.clean_df['game_score_normalized'] = 100 * self.clean_df['game_score'] / max_score
            else:
                self.clean_df['game_score_normalized'] = 0
        self.log_transform("Variable objetivo creada")
        return self

    def get_clean_data(self):
        return self.clean_df, self.transformations_log

    def save_clean_data(self, path):
        # Para evitar problemas con PyArrow al guardar listas en Parquet,
        # convertimos temporalmente las columnas tipo lista a strings de tipo JSON
        df_to_save = self.clean_df.copy()
        for col in df_to_save.columns:
            if col.endswith('_list'):
                df_to_save[col] = df_to_save[col].apply(json.dumps)

        # Eliminar columna tipo 'datetime64' si da conflicto o dejar que parquet la maneje nativamente
        df_to_save.to_parquet(path, index=False)
        self.log_transform(f"Dataset guardado en {path}")

        log_path = path.replace('.parquet', '_transformations.json')
        with open(log_path, 'w') as f:
            json.dump(self.transformations_log, f, indent=2)
        return self

"""* ============================================
# BLOQUE 4: EJECUCIÓN DEL AGENTE 1
* ============================================
"""

# Crear instancia del normalizador con el dataset original
normalizer = SteamDataNormalizer(df_raw)

print("="*60)
print("AGENTE 1: NORMALIZADOR - INICIANDO PROCESAMIENTO")
print("="*60)

# --- FASE 1: EXTRACCIÓN Y LIMPIEZA INICIAL ---
# 1. Limpiar precios (maneja texto, gratuidad y convierte a float)
normalizer.clean_prices()

# 2. Procesar reseñas (extrae sentimiento, conteo y porcentaje por separado)
normalizer.process_reviews()

# 3. Normalizar fechas (convierte a datetime y extrae características temporales)
normalizer.normalize_dates()

# 4. Procesar columnas de texto estructurado en listas (géneros, tags, idiomas)
for col in ['genre', 'popular_tags', 'languages']:
    if col in normalizer.clean_df.columns:
        normalizer.parse_list_column(col)


# --- FASE 2: TRATAMIENTO DE VALORES FALTANTES ---
# 5. Imputar valores faltantes de forma inteligente
# Se ejecuta AQUÍ para capturar los NaNs generados en los pasos anteriores de forma segura
normalizer.impute_missing_values()


# --- FASE 3: PREPARACIÓN PARA MACHINE LEARNING ---
# 6. Codificar variables categóricas clave (LabelEncoder seguro sin nulos)
categorical_cols = ['type', 'developer', 'publisher']
normalizer.encode_categorical(categorical_cols)

# 7. Escalar variables numéricas importantes (StandardScaler)
numeric_cols = ['price_clean', 'all_reviews_count', 'recent_reviews_count']
normalizer.scale_numeric([c for c in numeric_cols if c in normalizer.clean_df.columns])


# --- FASE 4: INGENIERÍA DE CARACTERÍSTICAS (TARGET) ---
# 8. Crear variable objetivo basada en popularidad y aceptación
normalizer.create_target_variable()

print("\n" + "="*60)
print("AGENTE 1: PROCESAMIENTO COMPLETADO")
print("="*60)

# Obtener dataframe limpio y bitácora de transformaciones
df_clean, transformations = normalizer.get_clean_data()

# Reporte de métricas del agente
print(f"\nDataset limpio dimensiones: {df_clean.shape}")
print(f"Nuevas columnas creadas: {len(df_clean.columns) - len(df_raw.columns)} nuevas (Total: {len(df_clean.columns)})")
print(f"Transformaciones registradas en el log: {len(transformations)}")

# Ver muestra del dataset procesado
print("\nMuestra del dataset limpio:")
df_clean.head()

